### ISSUE TITLE
new micro release

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.structure#27]
Because https://github.com/diffpy/diffpy.structure/pull/26 is quite troublesome in srfit.

**Comment by chiahaoliu** [comment]
@pavoljuhas poke :)

**Comment by pavoljuhas** [comment]
@chiahaoliu - trying to find time...

**Comment by chiahaoliu** [comment]
@pavoljuhas Sure! Please let me know if there is anything I can help with!

**Comment by pavoljuhas** [comment]
DONE - https://github.com/diffpy/diffpy.structure/releases/tag/v3.0.1

**Comment by chiahaoliu** [comment]
thanks so much @pavoljuhas
