### ISSUE TITLE
diffpy.structure vs. pyobjcryst

### ISSUE THREAD

**Issue by blokhin** [diffpy/diffpy.structure#54]
Dear colleagues,
Dear @vincefn,

Looking at the code, I expected `diffpy.structure` was dependent on `ObjCryst++` but in fact it's not. What is the architectural reason of keeping them independent if they (seem to) do very similar things?

FYI a website http://vincefn.net with some relevant docs is down.

**Comment by vincefn** [comment]
Dear @blokhin , I'm only involved in `pyobjcryst` and `libobjcryst`, so I don't know much about the other diffpy packages.
Probably @st3107 or @sbillinge can answer your question. It might be better to ask this on the mailing lists (https://www.diffpy.org/community.html) rather than open an issue here.

> FYI a website http://vincefn.net/ with some relevant docs is down.

Thanks - some issue with my VPS - it's back online.

**Comment by st3107** [comment]
Hi @blokhin . Yes, the diffpy.structure and pyobjectcryst (based on libobjcryst) are two independent packages. I am not the designer of the diffpy package so I don't know why they are developed separately.

**Comment by pavoljuhas** [comment]
diffpy.structure was developed first as a light-weight structure container for PDFgui.
It is a pure Python which makes it easier to install on Windows and thus makes it easier to distribute PDFgui.

pyobjcryst was developed several years later as a Python interface to much richer structure objects and functions in ObjCryst++.  As such it is more tricky to build on Windows - note we did not have conda-forge available at that time.
The use of pyobjcryst requires some familiarity with structure objects hierarchy and composition in ObjCryst++.

In the end the choice of structure package depends on your use case -
diffpy.structure is simpler and should suffice for simple tasks.
Use pyobjcryst if you need more advanced features / functions from ObjCryst++,
of if you are already familiar with ObjCryst++.

PS: For reference, libobjcryst is a fork of ObjCryst++ reduced to non-gui functions only.
It is used as a c++ backend for pyobjcryst.

**Comment by sbillinge** [comment]
@blokhin it is a great question.   It is mostly historical.
 Diffpy.structureis a lighter weight structure container that has most of
what is needed for PDF analysis of crystal structures,  including
symmetry.  We developed it before we started the wrapping of objcryst++ As
pyobjcryst, so at the time that functionality wasn't available in python.
Vincent had continued to develop pyobjcryst even more over time so this is
now a more powerful option but both are supported in diffpy-cmi so you can
use either.

**Comment by blokhin** [comment]
OK, many thanks for your kind answers. Closing now.
