### ISSUE TITLE
Numpy 2.0.0 Compatibility

### ISSUE THREAD

**Issue by Sparks29032** [diffpy/diffpy.structure#68]
Deprecations from `numpy 2.0.0` affect this package. Fix asap.

![image](https://github.com/diffpy/diffpy.structure/assets/59151395/c14dec55-24f3-4214-8c66-da440a8e6e3c)

**Comment by hakonanes** [comment]
Hi all, we're currently trying to make a package depending on diffpy.structure (orix) compatible with NumPy 2.0. Do you have an idea of what it would take to make diffpy.structure compatible with 2.0?

**Comment by sbillinge** [comment]
@hakonanes we are about ready to embark on this.  We have been updating our package repository structures and bringing things up to python 3.12.  We chose to pin to numpy<2 while we did that task.  But it is almost finished and then we will do the numpy 2 deprecations and errors.  I hope we can roll something out on the order of a week.

**Comment by hakonanes** [comment]
That sounds fantastic, we really appreciate it.

**Comment by hakonanes** [comment]
Hi folks, is there any timeline for when a NumPy v2-compatible release is available from PyPI and conda-forge (not an RC)?

**Comment by sbillinge** [comment]
@hakonanes we can push that out today.

**Comment by hakonanes** [comment]
Thanks, that would be great!

**Comment by sbillinge** [comment]
It is pushed to pypi.   @bobleesj  is pushing it up to conda-forge right now.
