### ISSUE TITLE
Fix ion error

### ISSUE THREAD

**Issue by Tieqiong** [diffpy/diffpy.structure#87]

**Comment by sbillinge** [comment]
@Tieqiong this needs more explanation or we won't know what it means in the future

**Comment by Tieqiong** [comment]
This issue in fact not seems to be in diffpy.structure. Sorry. Closing it.

**Comment by sbillinge** [comment]
but just to confirm, did you move the issue to diffpy.srfit or wherever the issue is happening?

**Comment by Tieqiong** [comment]
@sbillinge No I haven't yet. This problem is from diffpy.srreal, but the file it's wrapping is in libdiffpy. Should I make this issue in diffpy.srreal or libdiffpy?

**Comment by sbillinge** [comment]
I would make it in both places and then cross-reference them so they all close when one closes
