### ISSUE TITLE
"File not found" error in docs site

### ISSUE THREAD

**Issue by iurisegtovich** [diffpy/diffpy.structure#9]
* 404 - file not found error when trying to access  "http://diffpy.github.io/diffpy.Structure"

# ERROR

    404

    File not found

    The site configured at this address does not contain the requested file.

    If this is your site, make sure that the filename case matches the URL.
    For root URLs (like http://example.com/) you must provide an index.html file.

    Read the full documentation for more information about using GitHub Pages.

    GitHub Status — @githubstatus

# AT

    http://www.diffpy.org/diffpy.Structure

**Comment by pavoljuhas** [comment]
Thanks for the report, fixed with e8a68e1809d2569fe26308b3a8d702b21ddc2793.  The URL should point to diffpy.structure, but I have also added a redirect for the original one.
