### ISSUE TITLE
setuptools-git-versioning dependency

### ISSUE THREAD

**Issue by jlaehne** [diffpy/diffpy.structure#96]
Is there an important reason to pin `setuptools-git-versioning<2`?
https://github.com/diffpy/diffpy.structure/blob/9dc84df3e357fbbf4feaf08f7c37b5e580f97429/pyproject.toml#L2

It builds with v2 on my system.

**Comment by sbillinge** [comment]
@Sparks29032 or anyone know why we did this?

**Comment by Sparks29032** [comment]
We did that before version 2 came out in case version 2 breaks everything. Great it works on 2, let's upgrade!

**Comment by bobleesj** [comment]
Let's close this since we've implemented `setuptools-git-versioning>=2.0` both here https://github.com/diffpy/diffpy.structure/pull/102/ and the cookiecutter repo.
